#!/bin/sh
# Mock xbps-install: optionally log args, then create a minimal rootfs skeleton.
# Real xbps-install uses -r <rootfs> and needs -S to sync the remote index.
[ -n "$CRT_MOCK_LOG" ] && echo "xbps-install $* stdin=$(readlink /proc/$$/fd/0)" >> "$CRT_MOCK_LOG"
while [ $# -gt 0 ]; do
    case "$1" in
        -r) rootfs="$2"; shift 2 ;;
        *)  shift ;;
    esac
done
mkdir -p "$rootfs/bin" "$rootfs/etc" "$rootfs/usr/bin"
printf '#!/bin/sh\nexec /bin/sh "$@"\n' > "$rootfs/bin/sh"
chmod +x "$rootfs/bin/sh"
